### ISSUE TITLE
Decide what brush axes to use

### ISSUE THREAD

**Issue by jim-sheldon** [ds5110/stinky2#14]
The map needs some variables for the brush, using time for one might make sense.
For the other...temperature? wind? something else?

**Comment by jim-sheldon** [comment]
Wind speed vs wind direction?

**Comment by aaronfihn** [comment]
So options are really wind speed, wind direction, temperature, # of complaints, VOC readings, # of vessels, amount of shipped oil, time, and location?

These seem most sensible to me:
1. Temperature vs time, to explain that smells likely get worse in the summer
2. Complaints vs time might be interesting as an EDA tool for any follow-up on this.

I'll do the neighborhood regressions first to see if those give off valuable insights.
